version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
      - "22"

  kafka:
    image: helterscelter/kafka-docker
    expose:
      - "9092"
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
